name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.15.x]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -v ./...

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v -race ./...

  golangci:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest]  # TODO: also on: windows-latest, macos-latest
        go-version: [1.15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
